home:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\SecurityController::register

match:
  path: /match
  controller: App\Controller\MatchController::index
