home:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\SecurityController::register

tournaments:
  path: /tournaments
  controller: App\Controller\TournamentController::index

tournamentNew:
  path: /tournaments/new
  controller: App\Controller\TournamentController::new

tournamentEdit:
  path: /tournaments/{tournament}/edit
  controller: App\Controller\TournamentController::edit

tournamentRegistration:
  path: /tournaments/{tournament}/registration/{user}
  controller: App\Controller\TournamentController::registration