home:
  path: /
  controller: App\Controller\HomeController::index

security_login:
  path: /login
  controller: App\Controller\SecurityController::signin

security_logout:
  path: /logout

api_login_check:
  path: /api/login_check

verify_token:
  path: /api/verifytoken
  controller: App\Controller\ApiController::verify_token

create_token:
  path: /api/createtoken
  controller: App\Controller\ApiController::create_token

register:
  path: /register
  controller: App\Controller\SecurityController::register

tournaments:
  path: /tournaments
  controller: App\Controller\TournamentController::index

tournamentNew:
  path: /tournaments/new
  controller: App\Controller\TournamentController::new

tournamentEdit:
  path: /tournaments/{tournament}/edit
  controller: App\Controller\TournamentController::edit

tournamentRegistration:
  path: /tournaments/{tournament}/registration/{user}
  controller: App\Controller\TournamentController::registration

tournamentUnregistration:
  path: /tournaments/{tournament}/unregistration/{user}
  controller: App\Controller\TournamentController::unregistration

mesMatchs:
  path: /mesMatchs
  controller: App\Controller\MatchController::index
